global_config:
  openai_key:
    value: xxx
    env_name: OPENAI_API_KEY
solvers:
  all_pass_abstain_detector:
    input_name: response
    output_name: response
  spacy_response_decomposer:
    spacy_model: en_core_web_sm
    input_name: response
    output_name: sentences
  chatgpt_decontextualizer:
    input_name: sentences
    output_name: claims
  chatgpt_worthiness_filter:
    input_name: claims
    output_name: claims
  search_engine_evidence_retriever:
    search_engine: google
    url_merge_method: union
    input_name: claims
    output_name: evidences
  chat_gpt_claim_examiner:
    path_save_stance: evidence_stance.json
    num_retries: 3
    input_name: evidences
    output_name: claim_info
  chatgpt_post_editor:
    path_save_edited_claims: evidence_stance_edit.json
    num_retries: 3
    input_name: claim_info
    output_name: claim_info
  concat_response_generator:
    input_name: claim_info
    output_name: output