global_config:
  openai_key:
    value: xxx
    env_name: OPENAI_API_KEY
  serper_key:
    value: xxx
    env_name: SERPER_API_KEY
  scraper_key:
    value: xxx
    env_name: SCRAPER_API_KEY
solvers:
  all_pass_abstain_detector:
    input_name: response
    output_name: response
  factool_blackbox:
    llm_in_use: gpt-4
    input_prompt: question
    input_name: response
    output_name: claim_info
  factool_blackbox_post_editor:
    path_save_analysis: factool_evidence_analysis.json
    input_name: claim_info
    output_name: claim_info
  concat_response_generator:
    input_name: claim_info
    output_name: output